In [33]:
import pandas as pd
import csv

# Définition des noms de colonnes selon la requête SQL
columns = [
    'id',                    # ID auto-incrémental
    'id_local',             # Faits
    'title',
    'description',
    'type_contrat',         # Contrat
    'code_domaine',         # Domaine
    'nom_domaine',
    'code_postal',          # Lieu
    'ville',
    'departement',
    'region',
    'pays',
    'latitude',
    'longitude',
    'population',
    'mois_creation',        # Dates création
    'jour_creation',
    'mois_nom_creation',
    'jour_semaine_creation',
    'week_end_creation',
    'mois_modification',    # Dates modification
    'jour_modification',
    'mois_nom_modification',
    'jour_semaine_modification',
    'week_end_modification',
    'type_teletravail',     # Télétravail
    'type_seniorite',       # Seniorité
    'code_rome',            # Rome
    'nom_entreprise',       # Entreprise
    'categorie_entreprise',
    'date_creation_entreprise',
    'competences',          # Compétences concaténées
    'types_competences',
    'softskills_summary',   # Softskills concaténés
    'softskills_details',
    'nom_metier'            # Métiers concaténés
]

# Lecture du fichier avec les noms de colonnes spécifiés
df = pd.read_csv(
    filepath_or_buffer='../data/ONE_BIG_TABLE.csv.gz',
    sep=',',
    encoding='utf-8',
    quoting=csv.QUOTE_ALL,  # Force l'utilisation des guillemets pour tous les champs
    escapechar='\\',        # Définit le caractère d'échappement
    doublequote=True,       # Permet les guillemets doubles dans les champs
    on_bad_lines='warn',    # Avertit sur les lignes problématiques au lieu d'échouer
    names=columns,          # Utilise les noms de colonnes définis
    header=0               # La première ligne contient les en-têtes
)

df.head()

,id,id_local,title,description,type_contrat,code_domaine,nom_domaine,code_postal,ville,departement,...,type_seniorite,code_rome,nom_entreprise,categorie_entreprise,date_creation_entreprise,competences,types_competences,softskills_summary,softskills_details,nom_metier
0,4777,5239871433,Devops azure confirmé,DEVOPS AZURE (CDI) ILE DE FRANCE - 2 jours de ...,CDI,K16,Culture et gestion documentaire,75001.0,Paris,Paris,...,Senior,M1827,NaN,NaN,NaN,"Azure, DevOps, Kubernetes, Terraform","Cloud Computing, Containerization, DevOps",NaN,NaN,"Chef de groupe logicien informaticien, Devops,..."
1,1534,5243842723,Ingénieur DevOps H/F,Nos activités : - Pôle Compétences : activité ...,NaN,J13,Professionnels médico-techniques,44800.0,Saint-Herblain,Loire-Atlantique,...,NaN,M1827,AIS,PME,2018-10-05,NaN,NaN,NaN,NaN,"Chef de groupe logicien informaticien, Devops,..."
2,3518,5247807046,Expert Technique Kubernetes H/F,Propulse IT recherche pour un de ses clients g...,NaN,H12,"Conception, recherche, études et développement",75001.0,Paris,Paris,...,Senior,M1827,PROPULSE IT,PME,2014-01-22,"GitLab, Kubernetes, Vault","Containerization, Security, Version Control",NaN,NaN,"Chef de groupe logicien informaticien, Devops,..."
3,1780,5229955731,Ingénieur DevOps H/F,Maintenir les processus de déploiement automat...,NaN,H11,Affaires et support technique client,44000.0,Nantes,Loire-Atlantique,...,NaN,M1827,W CONRAN DESIGN,GE,1997-10-21,Maintenance,IT Operations,NaN,NaN,"Chef de groupe logicien informaticien, Devops,..."
4,2230,5251470933,Développeur Confirmé Front-End Vue.Js H/F,Notre client est un éditeur de logiciels d'ent...,NaN,H13,Hygiène Sécurité Environnement -HSE- industriels,35510.0,Cesson-Sévigné,Ille-et-Vilaine,...,Confirmé,M1827,SEYOS,PME,2014-01-14,Vue.js,Web Framework,NaN,NaN,"Chef de groupe logicien informaticien, Devops,..."